default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  template: template0

development:
  <<: *default
  database: sed-blog_development

test:
  <<: *default
  database: sed-blog_test

production:
  <<: *default
  database: sed-blog_production
